name: Deploy Portfolio from Private Repo

on:
  push:
    branches:
      - main  # Runs when pushing to main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repository (portfolio-private)
        uses: actions/checkout@v4
        with:
          repository: techcure/portfolio-private
          ref: main
          token: ${{ secrets.GHPAT }}  # Use the PAT to access the private repo

      - name: Debug - List Repository Contents
        run: |
          ls -R
        shell: bash

      - name: Prepare Artifact from Repository
        run: |
          mkdir -p artifact
          # Copy index.html and other necessary files into the artifact directory
          cp index.html artifact/
          # Optionally, copy other files or directories (e.g., css, js, images)
          cp -r css js images artifact/
          # Debug: List files in the artifact directory
          ls -R artifact
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: artifact  # Ensure this matches the directory created above

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2